# Server and networking settings
### SERVER
  # The IP the server should listen on.
  server_ip: '127.0.0.1'
  # ip: "0.0.0.0" # Use only if you know what you are doing. This will let other computers connect to the database!

  # The port the server should use.
  server_port: 1895

  password: "ExamplePasswordChangeMe"

  storagePath: "/tmp" # Only for testing